/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package principal;

/**
 *
 * @author Sofia Vargas
 */
public class mdiPrincipal extends javax.swing.JFrame {

    private jpFormularioCirculo objCirculo = new jpFormularioCirculo();
    private jpFormularioRectangulo objRectangulo = new jpFormularioRectangulo();
    private jpFormularioCuadrado objCuadrado = new jpFormularioCuadrado();
    private jpFormularioTriangulo objTriangulo = new jpFormularioTriangulo();
    private jpFormularioRombo objRombo = new jpFormularioRombo();
    private jpFormularioTrapecio objTrapecio = new jpFormularioTrapecio();
    
    private void inicializarFormularios(){
        
        jifFormularioCirculo.setContentPane(objCirculo);
        objCirculo.setSize(500,500);
        jifFormularioCirculo.setSize(500, 500);
        
        jifFormularioRectangulo.setContentPane(objRectangulo);
        objRectangulo.setSize(500,500);
        jifFormularioRectangulo.setSize(500, 500);
        
        jifFormularioCuadrado.setContentPane(objCuadrado);
        objCuadrado.setSize(500,500);
        jifFormularioCuadrado.setSize(500, 500);
        
        jifFormularioTriangulo.setContentPane(objTriangulo);
        objTriangulo.setSize(500,500);
        jifFormularioTriangulo.setSize(500, 500);
        
        jifFormularioRombo.setContentPane(objRombo);
        objRombo.setSize(500,500);
        jifFormularioRombo.setSize(500, 500);
        
        jifFormularioTrapecio.setContentPane(objTrapecio);
        objTrapecio.setSize(500,500);
        jifFormularioTrapecio.setSize(500, 500);
        
    }
    
    
    public mdiPrincipal() {
        initComponents();
        this.inicializarFormularios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jifFormularioCirculo = new javax.swing.JInternalFrame();
        jifFormularioRectangulo = new javax.swing.JInternalFrame();
        jifFormularioCuadrado = new javax.swing.JInternalFrame();
        jifFormularioTriangulo = new javax.swing.JInternalFrame();
        jifFormularioRombo = new javax.swing.JInternalFrame();
        jifFormularioTrapecio = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiFormularioCirculo = new javax.swing.JMenuItem();
        jmiFormularioRectangulo = new javax.swing.JMenuItem();
        jmiFormularioCuadrado = new javax.swing.JMenuItem();
        jmiFormularioTriangulo = new javax.swing.JMenuItem();
        jmiFormularioRombo = new javax.swing.JMenuItem();
        jmiFormularioTrapecio = new javax.swing.JMenuItem();
        jmiSalida = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifFormularioCirculo.setClosable(true);
        jifFormularioCirculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioCirculo.setVisible(false);

        javax.swing.GroupLayout jifFormularioCirculoLayout = new javax.swing.GroupLayout(jifFormularioCirculo.getContentPane());
        jifFormularioCirculo.getContentPane().setLayout(jifFormularioCirculoLayout);
        jifFormularioCirculoLayout.setHorizontalGroup(
            jifFormularioCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioCirculoLayout.setVerticalGroup(
            jifFormularioCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioCirculo);
        jifFormularioCirculo.setBounds(30, 0, 320, 280);

        jifFormularioRectangulo.setClosable(true);
        jifFormularioRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioRectangulo.setVisible(false);

        javax.swing.GroupLayout jifFormularioRectanguloLayout = new javax.swing.GroupLayout(jifFormularioRectangulo.getContentPane());
        jifFormularioRectangulo.getContentPane().setLayout(jifFormularioRectanguloLayout);
        jifFormularioRectanguloLayout.setHorizontalGroup(
            jifFormularioRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioRectanguloLayout.setVerticalGroup(
            jifFormularioRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioRectangulo);
        jifFormularioRectangulo.setBounds(20, 10, 360, 260);

        jifFormularioCuadrado.setClosable(true);
        jifFormularioCuadrado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioCuadrado.setVisible(false);

        javax.swing.GroupLayout jifFormularioCuadradoLayout = new javax.swing.GroupLayout(jifFormularioCuadrado.getContentPane());
        jifFormularioCuadrado.getContentPane().setLayout(jifFormularioCuadradoLayout);
        jifFormularioCuadradoLayout.setHorizontalGroup(
            jifFormularioCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioCuadradoLayout.setVerticalGroup(
            jifFormularioCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioCuadrado);
        jifFormularioCuadrado.setBounds(20, 10, 360, 260);

        jifFormularioTriangulo.setClosable(true);
        jifFormularioTriangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioTriangulo.setVisible(false);

        javax.swing.GroupLayout jifFormularioTrianguloLayout = new javax.swing.GroupLayout(jifFormularioTriangulo.getContentPane());
        jifFormularioTriangulo.getContentPane().setLayout(jifFormularioTrianguloLayout);
        jifFormularioTrianguloLayout.setHorizontalGroup(
            jifFormularioTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioTrianguloLayout.setVerticalGroup(
            jifFormularioTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioTriangulo);
        jifFormularioTriangulo.setBounds(20, 10, 360, 260);

        jifFormularioRombo.setClosable(true);
        jifFormularioRombo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioRombo.setVisible(false);

        javax.swing.GroupLayout jifFormularioRomboLayout = new javax.swing.GroupLayout(jifFormularioRombo.getContentPane());
        jifFormularioRombo.getContentPane().setLayout(jifFormularioRomboLayout);
        jifFormularioRomboLayout.setHorizontalGroup(
            jifFormularioRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioRomboLayout.setVerticalGroup(
            jifFormularioRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioRombo);
        jifFormularioRombo.setBounds(20, 10, 360, 270);

        jifFormularioTrapecio.setClosable(true);
        jifFormularioTrapecio.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioTrapecio.setVisible(false);

        javax.swing.GroupLayout jifFormularioTrapecioLayout = new javax.swing.GroupLayout(jifFormularioTrapecio.getContentPane());
        jifFormularioTrapecio.getContentPane().setLayout(jifFormularioTrapecioLayout);
        jifFormularioTrapecioLayout.setHorizontalGroup(
            jifFormularioTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioTrapecioLayout.setVerticalGroup(
            jifFormularioTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioTrapecio);
        jifFormularioTrapecio.setBounds(20, 10, 360, 260);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        jmiFormularioCirculo.setMnemonic('o');
        jmiFormularioCirculo.setText("Circulo");
        jmiFormularioCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioCirculoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormularioCirculo);

        jmiFormularioRectangulo.setMnemonic('s');
        jmiFormularioRectangulo.setText("Rectangulo");
        jmiFormularioRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioRectanguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormularioRectangulo);

        jmiFormularioCuadrado.setMnemonic('a');
        jmiFormularioCuadrado.setText("Cuadrado");
        jmiFormularioCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioCuadradoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormularioCuadrado);

        jmiFormularioTriangulo.setText("Triangulo");
        jmiFormularioTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioTrianguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormularioTriangulo);

        jmiFormularioRombo.setText("Rombo");
        jmiFormularioRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioRomboActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormularioRombo);

        jmiFormularioTrapecio.setText("Trapecio");
        jmiFormularioTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioTrapecioActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormularioTrapecio);

        jmiSalida.setMnemonic('x');
        jmiSalida.setText("Salir");
        jmiSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalidaActionPerformed(evt);
            }
        });
        fileMenu.add(jmiSalida);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalidaActionPerformed

    private void jmiFormularioRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioRectanguloActionPerformed
        jifFormularioRectangulo.setVisible(true);
    }//GEN-LAST:event_jmiFormularioRectanguloActionPerformed

    private void jmiFormularioTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioTrapecioActionPerformed
        jifFormularioTrapecio.setVisible(true);
    }//GEN-LAST:event_jmiFormularioTrapecioActionPerformed

    private void jmiFormularioCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioCirculoActionPerformed
    jifFormularioCirculo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jmiFormularioCirculoActionPerformed

    private void jmiFormularioCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioCuadradoActionPerformed
        jifFormularioCuadrado.setVisible(true);
    }//GEN-LAST:event_jmiFormularioCuadradoActionPerformed

    private void jmiFormularioTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioTrianguloActionPerformed
        jifFormularioTriangulo.setVisible(true);
    }//GEN-LAST:event_jmiFormularioTrianguloActionPerformed

    private void jmiFormularioRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioRomboActionPerformed
        jifFormularioRombo.setVisible(true);
    }//GEN-LAST:event_jmiFormularioRomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JInternalFrame jifFormularioCirculo;
    private javax.swing.JInternalFrame jifFormularioCuadrado;
    private javax.swing.JInternalFrame jifFormularioRectangulo;
    private javax.swing.JInternalFrame jifFormularioRombo;
    private javax.swing.JInternalFrame jifFormularioTrapecio;
    private javax.swing.JInternalFrame jifFormularioTriangulo;
    private javax.swing.JMenuItem jmiFormularioCirculo;
    private javax.swing.JMenuItem jmiFormularioCuadrado;
    private javax.swing.JMenuItem jmiFormularioRectangulo;
    private javax.swing.JMenuItem jmiFormularioRombo;
    private javax.swing.JMenuItem jmiFormularioTrapecio;
    private javax.swing.JMenuItem jmiFormularioTriangulo;
    private javax.swing.JMenuItem jmiSalida;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
